# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/roysi/Files/URSS/Verilog/Constraint files/clocks.xdc

# XDC: C:/Users/roysi/Files/URSS/Verilog/Constraint files/ports.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_zero_detector_0_0/design_1_zero_detector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zero_detector_0_0 || ORIG_REF_NAME==design_1_zero_detector_0_0}]

# IP: bd/design_1/ip/design_1_lp_filter_2_0_0/design_1_lp_filter_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lp_filter_2_0_0 || ORIG_REF_NAME==design_1_lp_filter_2_0_0}]

# IP: bd/design_1/ip/design_1_cfd_0_0_1/design_1_cfd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cfd_0_0 || ORIG_REF_NAME==design_1_cfd_0_0}]

# XDC: bd/design_1/design_1_ooc.xdc
